newIssueComment: >
  Thanks for opening this issue! Be sure to include full details of your bug/suggestion.

newPRComment: >
  Thanks for opening this pull request!

newComment: >
  Thanks for the comment!